### ISSUE TITLE
Dreambox 900 Kodi SSL Error

### ISSUE THREAD

**Issue by einmalacht** [hubsif/kodi-magentasport#20]
Hallo beim laden des Plugin bekomm ich folgende Fehlermeldung im Log 

21:35:54.356 T:2873279360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.telekomsport/default.py", line 329, in <module>
                                                locals()['get' + mode]()
                                              File "/root/.kodi/addons/plugin.video.telekomsport/default.py", line 102, in getMain
                                                response = urllib.urlopen(base_url + main_page).read()
                                              File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
                                                return opener.open(url)
                                              File "/usr/lib/python2.7/urllib.py", line 213, in open
                                                return getattr(self, name)(url)
                                              File "/usr/lib/python2.7/urllib.py", line 443, in open_https
                                                h.endheaders(data)
                                              File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
                                                self._send_output(message_body)
                                              File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
                                                self.send(msg)
                                              File "/usr/lib/python2.7/httplib.py", line 859, in send
                                                self.connect()
                                              File "/usr/lib/python2.7/httplib.py", line 1278, in connect
                                                server_hostname=server_hostname)
                                              File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
                                                _context=self)
                                              File "/usr/lib/python2.7/ssl.py", line 579, in __init__
                                                self.do_handshake()
                                              File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
                                                self._sslobj.do_handshake()
                                            IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
                                            -->End of Python script error report<--
21:35:54.377 T:2873279360    INFO: Python script stopped

Was könnte das für ein Problem sein?

**Comment by hubsif** [comment]
Hi einmalacht,

es sieht so aus, als könne Python auf deiner Dreambox das HTTPS-Zertifikat der Telekom nicht bestätigen. Das kann mehrere Gründe haben. Der wahrscheinlichste ist für mich, dass das CA-Zertifikat (von Digicert) fehlt. Hatte es denn mal funktioniert oder hast du das Addon neu installiert?

Falls es noch nie ging: Die Digicert-CA ist relativ neu, gibt es evtl. Updates der Dreambox, die das neue Zertifikat mitbringen können?
Ansonsten könnte ich noch einbauen, dass das Zertifikat nicht überprüft werden soll. Das würde ich aber dann einstellbar machen, denn das möchte man ja eigentlich vermeiden.

**Comment by einmalacht** [comment]
Hi hubsif,
danke für die schnelle Rückmeldung ... ich hab das erstmalig probiert auf der Dream.
Ich schau mir das nochmal an jetzt weiss ich ja wo ich ungefähr suchen muss.
Danke

**Comment by hubsif** [comment]
Hi einmalacht,
Konntest du dein Problem lösen?

**Comment by betacentauri** [comment]
Das hier funktioniert:
https://github.com/E2OpenPlugins/e2openplugin-TelekomSport/blob/master/plugin/plugin.py#L38
Ist nicht toll, aber die Dreamboxen haben wohl generell ein Problem damit.
