### ISSUE TITLE
Version 2.1.0 (Matrix Upgrade) spielt keine kostenpflichtige Inhalte mehr ab

### ISSUE THREAD

**Issue by uhafner** [hubsif/kodi-magentasport#36]
Ich bin auf Kodi 19 (Matrix) umgestiegen und habe das neue Plugin 2.1.0 installiert. Leider lassen sich keine bezahlten Inhalte abspielen, ich bekomme eine Exception im Log:

```
2021-04-04 09:18:06.339 T:34640    INFO <general>: CPythonInvoker(46, /home/hafner/.kodi/addons/plugin.video.magentasport/default.py): script successfully run
2021-04-04 09:18:06.364 T:34640    INFO <general>: Python interpreter stopped
2021-04-04 09:18:08.717 T:34642    INFO <general>: initializing python engine.
2021-04-04 09:18:08.799 T:34642 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-04-04 09:18:09.269 T:34642   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
                                                   Traceback (most recent call last):
                                                     File "/home/hafner/.kodi/addons/plugin.video.magentasport/default.py", line 297, in <module>
                                                       locals()['get' + mode]()
                                                     File "/home/hafner/.kodi/addons/plugin.video.magentasport/default.py", line 258, in getvideo
                                                       auth_response = auth_media(jwt, videoid)
                                                     File "/home/hafner/.kodi/addons/plugin.video.magentasport/default.py", line 85, in auth_media
                                                       urllib.request.urlopen(urllib.request.Request(heartbeat_url + '/destroy', "", {'xauthorization': jwt, 'Content-Type': 'application/json'})).read()
                                                     File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 514, in open
                                                       req = meth(req)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1277, in do_request_
                                                       raise TypeError(msg)
                                                   TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
                                                   -->End of Python script error report<--
                                                   
2021-04-04 09:18:09.293 T:34642    INFO <general>: Python interpreter stopped
2021-04-04 09:18:09.302 T:893     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.magentasport/?mode=video&videoid=283954&isPay=True]
```

Bei einem Video aus dem nicht bezahlten Bereich kommt:
```
2021-04-04 09:13:42.847 T:34464    INFO <general>: initializing python engine.
2021-04-04 09:13:42.928 T:34464 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-04-04 09:13:43.135 T:34464    INFO <general>: CPythonInvoker(45, /home/hafner/.kodi/addons/plugin.video.magentasport/default.py): script successfully run
2021-04-04 09:13:43.160 T:34464    INFO <general>: Python interpreter stopped
2021-04-04 09:13:43.161 T:893      INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.magentasport/?mode=video&videoid=283958&isPay=False
2021-04-04 09:13:43.321 T:34466 WARNING <general>: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
2021-04-04 09:13:43.322 T:34466    INFO <general>: Creating InputStream
2021-04-04 09:13:43.322 T:34466   ERROR <general>: CInputStreamAddon::Supports - 'inputstreamaddon' has been deprecated, please use `#KODIPROP:inputstream=inputstream.adaptive` instead
2021-04-04 09:13:43.368 T:34466    INFO <general>: Creating Demuxer
2021-04-04 09:13:43.466 T:983   WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-04-04 09:13:45.610 T:34466    INFO <general>: Opening stream: 8 source: 256
2021-04-04 09:13:45.610 T:34466    INFO <general>: Creating video codec with codec id: 27
2021-04-04 09:13:45.610 T:34466    INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2021-04-04 09:13:45.610 T:34466    INFO <general>: Creating video thread
2021-04-04 09:13:45.610 T:34468    INFO <general>: running thread: video_thread
2021-04-04 09:13:45.611 T:34466    INFO <general>: Opening stream: 9 source: 256
2021-04-04 09:13:45.611 T:34466    INFO <general>: Finding audio codec for: 86018
2021-04-04 09:13:45.612 T:34466    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2021-04-04 09:13:45.612 T:34466    INFO <general>: Creating audio thread
2021-04-04 09:13:45.612 T:34469    INFO <general>: running thread: CVideoPlayerAudio::Process()
2021-04-04 09:13:45.623 T:34469    INFO <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2021-04-04 09:13:45.634 T:949      INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-04-04 09:13:45.641 T:34468    INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2021-04-04 09:13:45.699 T:893      INFO <general>: GL: Selecting YUV 2 RGB shader
2021-04-04 09:13:45.700 T:893      INFO <general>: GL: Using GL_ARB_pixel_buffer_object
2021-04-04 09:13:45.700 T:893      INFO <general>: Using GL_TEXTURE_2D
2021-04-04 09:13:45.835 T:949      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=PCH,DEV=0"
2021-04-04 09:13:45.838 T:949      INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=PCH,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02"
2021-04-04 09:13:45.838 T:949      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-04-04 09:13:45.838 T:949      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2021-04-04 09:13:46.133 T:34468    INFO <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 20000
```

Wenn ich dann wieder das Plugin 2.0.0 in Kodi 18 starte, geht alles wie geschmiert. Scheint wohl an der Umstellung zu liegen.

(Das andere Magentasport Plugin geht bei mir auch nicht, da dort neuerdings ein Bestätigungscode per mail geschickt wird, den man dann nirgends eingeben kann)

**Comment by hubsif** [comment]
Hi!
Danke für die Info, da war wohl noch ein Bug.
Ich habe gerade ein Update hochgeladen (v2.1.1), versuch mal bitte ob es damit geht.

**Comment by uhafner** [comment]
Super, die Version 2.1.1 funktioniert! Vielen Dank für das schnelle Update!
